// data.js
export const movieData = [
    {
        title: "The Wailing",
        pics: "The_Wailing.jpg",
        background: 'The_Wailing.jpg',
        epilogue: "In a remote village, a mysterious illness spreads after a stranger's arrival. A local police officer, trying to solve the mystery and protect his daughter, finds himself entangled in a series of bizarre events. 'The Wailing' is a horror-thriller that blends superstition, folklore, and shamanism.",
        DateReleased: "2016-05-12",
        category: "Horror, Mystery, Thriller",
        type: "Feature Film",
        actors: ["Kwak Do-won", "Hwang Jung-min", "Chun Woo-hee"],
        triller: "https://www.youtube.com/watch?v=43uAputjI4k",
        rating: 5,
        keywords: ["horror", "shamanism", "mystery", "superstition"],
        kind: "G",
        duration: "156 minutes",
        director: "Na Hong-jin"
    },
    {
        title: "Monstrum",
        pics: "Monstrum.jpg",
        epilogue: "Set in the Joseon era, 'Monstrum' follows a legendary general who is called upon to protect the kingdom from a terrifying monster that is rumored to be spreading a deadly plague. The film blends action, horror, and historical drama in a thrilling tale of heroism.",
        dateReleased: "2018-09-12",
        category: "Action, Horror, Historical",
        type: "Feature Film",
        actors: ["Kim Myung-min", "Kim In-kwon", "Lee Hye-ri"],
        triller: "https://www.youtube.com/watch?v=jzJnrGZhTL4",
        rating: 4.0,
        keywords: ["monster", "historical", "action", "plague"],
        kind: "PG",
        duration: "105 minutes",
        director: "Heo Jong-ho"
    },
    {
        title: "Jumong",
        pics: 'Jumong.jpg',
        epilogue: "A historical epic that chronicles the life of Jumong, the founder of Goguryeo, one of the three kingdoms of Korea. This sweeping drama delves into his rise to power, political intrigue, and battles as he strives to unite the kingdom.",
        DateReleased: "2006-05-15",
        category: "Action, Historical, Drama",
        type: "TV Series",
        actors: ["Song Il-gook", "Han Hye-jin", "Kim Seung-soo"],
        triller: "https://www.youtube.com/watch?v=Ih31tlb-QoM",
        rating: 4.5,
        keywords: ["historical", "epic", "founder", "Goguryeo"],
        kind: "PG",
        duration: "81 episodes",
        director: "Lee Joo-hwan"
    },
    {
        title: "Alchemy of Souls",
        pics: "Alchemy_of_Souls.jpg",
        epilogue: "In a world where the souls of the dead can possess the living, 'Alchemy of Souls' follows the story of a powerful mage trapped in a weak body and her encounter with a nobleman who wants to change his destiny. A fantasy epic filled with magic, love, and intrigue.",
        DateReleased: "2022-06-18",
        category: "Fantasy, Romance, Action",
        type: "TV Series",
        actors: ["Lee Jae-wook", "Jung So-min", "Hwang Min-hyun"],
        triller: "https://www.youtube.com/watch?v=x3zXzWwXfX4",
        rating: 3.5,
        keywords: ["fantasy", "romance", "magic", "destiny"],
        kind: "PG",
        duration: "30 episodes",
        director: "Park Joon-hwa"
    },
    {
        title: "Along with the Gods",
        pics: "Along_with_the_Gods.jpg",
        epilogue: "After a heroic death, a firefighter is guided through the afterlife by three guardians as he faces trials to determine his fate in the afterlife. 'Along with the Gods' is a visually stunning fantasy film that explores themes of redemption and moral judgment.",
        DateReleased: "2017-12-20",
        category: "Action, Fantasy, Drama",
        type: "Feature Film",
        actors: ["Ha Jung-woo", "Cha Tae-hyun", "Ju Ji-hoon"],
        triller: "https://www.youtube.com/watch?v=NrYAGH1y-4E",
        rating: 4.6,
        keywords: ["afterlife", "fantasy", "trials", "redemption"],
        kind: "PG",
        duration: "139 minutes",
        director: "Kim Yong-hwa"
    },
    {
        title: "A Werewolf Boy",
        pics: "A_Werewolf_Boy.jpg",
        epilogue: "A teenage girl moves to the countryside for her health and discovers a feral boy who behaves like a wolf. As she begins to tame him, a bond grows between them. 'A Werewolf Boy' is a heartwarming fantasy romance that tugs at the heartstrings.",
        DateReleased: "2012-10-31",
        category: "Fantasy, Romance, Drama",
        type: "Feature Film",
        actors: ["Song Joong-ki", "Park Bo-young", "Yoo Yeon-seok"],
        triller: "https://www.youtube.com/watch?v=_cZrAF06X-U",
        rating: 4.4,
        keywords: ["werewolf", "romance", "fantasy", "bond"],
        kind: "G",
        duration: "125 minutes",
        director: "Jo Sung-hee"
    },
    {
        title: "The Divine Fury",
        pics: "The_Divine_Fury.jpg",
        epilogue: "After losing his father at a young age, a champion MMA fighter seeks revenge and turns to an exorcist for help. 'The Divine Fury' blends action, horror, and supernatural elements as the fighter battles against dark forces threatening the world.",
        DateReleased: "2019-07-31",
        category: "Action, Horror, Supernatural",
        type: "Feature Film",
        actors: ["Park Seo-joon", "Ahn Sung-ki", "Woo Do-hwan"],
        triller: "https://www.youtube.com/watch?v=0MW7gS0R0lg",
        rating: 4.1,
        keywords: ["supernatural", "exorcism", "action", "revenge"],
        kind: "PG",
        duration: "129 minutes",
        director: "Kim Joo-hwan"
    },
    {
        title: "The Start-Up",
        pics: "The_Start_Up.jpg",
        background: "The_Start_Up.jpg",
        epilogue: "Set in the dynamic world of start-ups, this drama follows the journey of Seo Dal-mi, a young woman who dreams of becoming Korea's Steve Jobs. Alongside a brilliant but underachieving tech genius, Nam Do-san, they navigate the ups and downs of entrepreneurship, love, and friendship in a highly competitive industry.",
        DateReleased: "2020-10-17",
        category: "Drama, Romance",
        type: "TV Series",
        actors: ["Bae Suzy", "Nam Joo-hyuk", "Kim Seon-ho"],
        triller: "https://www.youtube.com/watch?v=GtSjhdm-Qmw",
        rating: 4.5,
        keywords: ["start-up", "entrepreneurship", "romance", "tech"],
        kind: "G",
        duration: "16 episodes",
        director: "Oh Choong-hwan"
    },
    {
        title: "Train to Busan",
        pics: "Train to Busan.jpg",
        epilogue: "A zombie outbreak occurs in South Korea, and passengers aboard a fast train from Seoul to Busan must fight for their survival. As the infection spreads rapidly through the train, a father and his daughter, along with a group of other passengers, struggle to stay alive in this intense, action-packed horror thriller.",
        DateReleased: "2016-07-20",
        category: "Horror, Action, Thriller",
        type: "Feature Film",
        actors: ["Gong Yoo", "Ma Dong-seok", "Jung Yu-mi"],
        triller: "https://www.youtube.com/watch?v=pyWuHv2-Abk",
        rating: 5,
        keywords: ["zombies", "survival", "action", "thriller"],
        kind: "PG",
        duration: "118 minutes",
        director: "Yeon Sang-ho"
    },
    {
        title: "The Witch",
        pics: "The_Witch.jpg",
        epilogue: "A high school student with no memory of her past is thrust into a world of danger after participating in a nationally televised competition. 'The Witch: Part 1. The Subversion' is a gripping action-thriller that delves into government conspiracies, superhuman abilities, and a mysterious past.",
        DateReleased: "2018-06-27",
        category: "Action, Mystery, Thriller",
        type: "Feature Film",
        actors: ["Kim Da-mi", "Jo Min-su", "Choi Woo-shik"],
        triller: "https://www.youtube.com/watch?v=Fz7HmgPJQak",
        rating: 4.3,
        keywords: ["superpowers", "conspiracy", "thriller", "mystery"],
        kind: "PG",
        duration: "125 minutes",
        director: "Park Hoon-jung"
    },
    {
        title: "Burning",
        pics: "Burning.jpg",
        epilogue: "A part-time worker, Jong-su, reunites with an old acquaintance, Hae-mi, who asks him to look after her cat while she travels. Upon her return, she introduces Ben, a mysterious and wealthy man with a strange hobby. 'Burning' is a psychological thriller that explores obsession, jealousy, and social inequality.",
        DateReleased: "2018-05-17",
        category: "Drama, Mystery, Thriller",
        type: "Feature Film",
        actors: ["Yoo Ah-in", "Steven Yeun", "Jeon Jong-seo"],
        triller: "https://www.youtube.com/watch?v=oihHs2Errwk",
        rating: 4.6,
        keywords: ["psychological", "mystery", "thriller", "obsession"],
        kind: "R",
        duration: "148 minutes",
        director: "Lee Chang-dong"
    },
    {
        title: "The Handmaiden",
        pics: "The_Hand_Maiden.jpg",
        epilogue: "Set in the 1930s during Japanese-occupied Korea, 'The Handmaiden' follows a young woman hired as a handmaiden to a Japanese heiress. However, she is secretly involved in a plot to defraud the heiress. Twists and turns abound in this visually stunning erotic thriller from director Park Chan-wook.",
        DateReleased: "2016-06-01",
        category: "Drama, Thriller, Romance",
        type: "Feature Film",
        actors: ["Kim Min-hee", "Kim Tae-ri", "Ha Jung-woo"],
        triller: "https://www.youtube.com/watch?v=whldChqCsYk",
        rating: 4.8,
        keywords: ["thriller", "romance", "deception", "erotic"],
        kind: "R",
        duration: "145 minutes",
        director: "Park Chan-wook"
    },
    {
        title: "The Host",
        pics: 'The_Host.jpg',
        epilogue: "A monstrous creature emerges from the Han River and begins terrorizing Seoul. A family sets out to rescue their youngest member, who has been taken by the creature. 'The Host' is a gripping monster movie that blends action, horror, and dark humor, while also critiquing environmental negligence.",
        DateReleased: "2006-07-27",
        category: "Action, Horror, Sci-Fi",
        type: "Feature Film",
        actors: ["Song Kang-ho", "Byun Hee-bong", "Park Hae-il"],
        triller: "https://www.youtube.com/watch?v=2pPSSKcPEJ8",
        rating: 5,
        keywords: ["monster", "action", "horror", "environment"],
        kind: "PG-13",
        duration: "120 minutes",
        director: "Bong Joon-ho"
    },
    {
        title: "The King",
        pics: "The_King.jpg",
        epilogue: "A young prosecutor rises to power in the corrupt world of politics and law enforcement, only to find himself entangled in a dangerous game of ambition and betrayal. 'The King' is a slick and stylish crime drama that explores the dark side of power in modern South Korea.",
        DateReleased: "2017-01-18",
        category: "Crime, Drama",
        type: "Feature Film",
        actors: ["Jo In-sung", "Jung Woo-sung", "Kim Ah-joong"],
        triller: "https://www.youtube.com/watch?v=jwM5C8s4D3I",
        rating: 4.3,
        keywords: ["crime", "power", "corruption", "betrayal"],
        kind: "R",
        duration: "134 minutes",
        director: "Han Jae-rim"
    },
    {
        title: "Spring, Summer, Fall, Winter... and Spring",
        pics: "Spring_Summer_Fall_Winter_and_Spring.jpg",
        epilogue: "This visually poetic film follows the life of a Buddhist monk over the course of the four seasons, symbolizing different stages of life. 'Spring, Summer, Fall, Winter... and Spring' is a meditative exploration of the cyclical nature of existence, spiritual growth, and the impact of one's actions.",
        DateReleased: "2003-09-19",
        category: "Drama, Spiritual",
        type: "Feature Film",
        actors: ["Oh Yeong-su", "Kim Young-min", "Seo Jae-kyung"],
        triller: "https://www.youtube.com/watch?v=t0mr9Dfp1uk",
        rating: 4.7,
        keywords: ["spiritual", "life cycle", "meditative", "drama"],
        kind: "PG-13",
        duration: "103 minutes",
        director: "Kim Ki-duk"
    },
    {
        title: "A Taxi Driver",
        pics: 'A_Taxi_Driver.jpg',
        epilogue: "Based on true events, 'A Taxi Driver' tells the story of a Seoul taxi driver who unwittingly becomes involved in the 1980 Gwangju Uprising when he drives a German journalist to the heart of the conflict. The film is a powerful historical drama that sheds light on one of South Korea's darkest moments.",
        DateReleased: "2017-08-02",
        category: "Drama, History",
        type: "Feature Film",
        actors: ["Song Kang-ho", "Thomas Kretschmann", "Yoo Hae-jin"],
        triller: "https://www.youtube.com/watch?v=8M8gCszKge8",
        rating: 4.7,
        keywords: ["history", "uprising", "democracy", "drama"],
        kind: "PG-13",
        duration: "137 minutes",
        director: "Jang Hoon"
    },
    {
        title: "Mother",
        pics: 'Mother.jpg',
        epilogue: "A devoted mother sets out to prove the innocence of her mentally challenged son, who has been accused of murder. 'Mother' is a suspenseful and emotionally charged thriller that explores the lengths a mother will go to protect her child, even as she uncovers unsettling truths.",
        DateReleased: "2009-05-28",
        category: "Drama, Thriller, Mystery",
        type: "Feature Film",
        actors: ["Kim Hye-ja", "Won Bin", "Jin Goo"],
        triller: "https://www.youtube.com/watch?v=97eM5C-qY_M",
        rating: 4.5,
        keywords: ["mother", "thriller", "murder", "suspense"],
        kind: "R",
        duration: "128 minutes",
        director: "Bong Joon-ho"
    },
    {
        title: "Parasite",
        pics: 'Parasite.jpg',
        epilogue: "A struggling lower-class family schemes to infiltrate the household of a wealthy family by taking over their domestic roles. 'Parasite' is a darkly comedic thriller that examines class inequality, greed, and the blurred lines between the rich and the poor. The film won the Palme d'Or at Cannes and the Academy Award for Best Picture.",
        DateReleased: "2019-05-30",
        category: "Drama, Thriller, Comedy",
        type: "Feature Film",
        actors: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong"],
        triller: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
        rating: 5.0,
        keywords: ["class", "inequality", "thriller", "comedy"],
        kind: "R",
        duration: "132 minutes",
        director: "Bong Joon-ho"
    },
    {
        title: "The Man from Nowhere",
        pics: 'The_Man_from_Nowhere.jpg',
        epilogue: "A reclusive pawnshop owner with a violent past becomes involved in a deadly situation when a young girl, his only friend, is kidnapped by a drug-trafficking ring. 'The Man from Nowhere' is a gripping action-thriller that features intense fight scenes and emotional depth.",
        DateReleased: "2010-08-04",
        category: "Action, Thriller",
        type: "Feature Film",
        actors: ["Won Bin", "Kim Sae-ron", "Kim Tae-hoon"],
        triller: "https://www.youtube.com/watch?v=38rPoGSr19U",
        rating: 4.6,
        keywords: ["action", "thriller", "revenge", "kidnapping"],
        kind: "R",
        duration: "119 minutes",
        director: "Lee Jeong-beom"
    },
    {
        title: "Silenced",
        pics: 'Silenced.jpg',
        epilogue: "Based on a true story, 'Silenced' follows a newly appointed teacher who discovers a horrifying secret at a school for hearing-impaired children. As he fights to bring justice to the victims of abuse, he faces resistance from a corrupt system. This powerful drama exposes societal injustices and sparked real-life reforms in South Korea.",
        DateReleased: "2011-09-22",
        category: "Drama, Crime",
        type: "Feature Film",
        actors: ["Gong Yoo", "Jung Yu-mi", "Kim Hyun-soo"],
        triller: "https://www.youtube.com/watch?v=AyYTwqndO1M",
        rating: 4.7,
        keywords: ["crime", "drama", "justice", "abuse"],
        kind: "R"
    },
    {
        title: "The Chaser",
        pics: 'The_Chaser.jpg',
        epilogue: "A former detective turned pimp realizes that several of his prostitutes have gone missing. As he investigates, he uncovers a shocking truth: a psychopathic serial killer is on the loose. 'The Chaser' is a tense and fast-paced thriller that keeps the audience on the edge of their seats.",
        DateReleased: "2008-02-14",
        category: "Thriller, Crime",
        type: "Feature Film",
        actors: ["Kim Yoon-seok", "Ha Jung-woo", "Seo Young-hee"],
        triller: "https://www.youtube.com/watch?v=qt_kUte7gag",
        rating: 4.5,
        keywords: ["thriller", "crime", "serial killer", "detective"],
        kind: "R"
    },
    {
        title: "Joint Security Area",
        pics: 'Joint_Security_Area.jpg',
        epilogue: "Set in the Korean Demilitarized Zone (DMZ), 'JSA' follows an investigation into a shooting incident that takes place along the border between North and South Korea. The film explores the complex relationships between soldiers from both sides and the underlying tensions of a divided nation.",
        DateReleased: "2000-09-09",
        category: "Drama, Thriller",
        type: "Feature Film",
        actors: ["Lee Byung-hun", "Song Kang-ho", "Lee Young-ae"],
        triller: "https://www.youtube.com/watch?v=vF4ocsojS9E",
        rating: 4.6,
        keywords: ["military", "border", "thriller", "drama"],
        kind: "R"
    },
    {
        title: "Ode to My Father",
        pics: 'Ode_to_My_Father.jpg',
        epilogue: "A sweeping epic that follows the life of a man from his childhood during the Korean War to his later years as a successful businessman. 'Ode to My Father' is a heartfelt drama that chronicles the struggles and sacrifices of a generation through one man's personal journey.",
        DateReleased: "2014-12-17",
        category: "Drama, History",
        type: "Feature Film",
        actors: ["Hwang Jung-min", "Kim Yun-jin", "Oh Dal-su"],
        triller: "https://www.youtube.com/watch?v=9YxkXP8gpeY",
        rating: 4.4,
        keywords: ["history", "family", "sacrifice", "drama"],
        kind: "PG-13"
    },
    {
        title: "The Good, The Bad, The Weird",
        pics: 'The_Good_The_Bad.jpg',
        epilogue: "Set in 1930s Manchuria, this action-packed Western-style film follows three men as they hunt for treasure in a lawless land. 'The Good, The Bad, The Weird' combines thrilling action sequences with humor and adventure, paying homage to classic Westerns with a unique Korean twist.",
        DateReleased: "2008-07-17",
        category: "Action, Adventure",
        type: "Feature Film",
        actors: ["Song Kang-ho", "Lee Byung-hun", "Jung Woo-sung"],
        triller: "https://www.youtube.com/watch?v=OzNnCK5cd8Q",
        rating: 4.3,
        keywords: ["action", "adventure", "western", "treasure"],
        kind: "R"
    },
    {
        title: "My Sassy Girl",
        pics: 'My_Sassy_Girl.jpg',
        epilogue: "A college student finds his life turned upside down when he meets a feisty and unpredictable young woman. 'My Sassy Girl' is a romantic comedy that became a cultural phenomenon, charming audiences with its unique blend of humor, romance, and heartfelt moments.",
        DateReleased: "2001-07-27",
        category: "Romantic Comedy",
        type: "Feature Film",
        actors: ["Jun Ji-hyun", "Cha Tae-hyun", "Kim In-mun"],
        triller: "https://www.youtube.com/watch?v=XkLqAlIETkA",
        rating: 4.2,
        keywords: ["romance", "comedy", "love", "relationship"],
        kind: "PG-13"
    },
    {
        title: "Gonjiam Haunted Asylum",
        pics: 'Gonjiam_Haunted_Asylum.jpg',
        epilogue: "A group of YouTubers explores the infamous Gonjiam Psychiatric Hospital, aiming to broadcast a live horror experience. Their excitement soon turns to terror as they encounter paranormal phenomena that exceed their worst fears. The film masterfully blends found-footage horror with jump scares, keeping viewers on edge. It's a spine-chilling journey into one of Korea's most haunted locations.",
        date_released: "March 28, 2018",
        category: "Horror, Thriller",
        type: "Feature Film",
        actors: ["Wi Ha-joon", "Oh Ah-yeon", "Park Ji-a", "Yoo Je-yoon", "Moon Ye-won"],
        trailer: "https://www.youtube.com/watch?v=6tVbyPrKPno",
        rating: 4.0,
        keywords: ["found footage", "asylum", "YouTubers", "paranormal", "horror"],
        kind: "R"
    },
    {
        title: "Metamorphosis",
        pics: 'Metamorphosis.jpg',
        epilogue: "A demonic entity that can change its appearance infiltrates a family, sowing mistrust and terror among them. The priest in the family tries to confront the evil, but it proves to be more powerful than expected. This movie brings a terrifying blend of psychological horror and exorcism themes.",
        date_released: "August 21, 2019",
        category: "Horror, Thriller",
        type: "Feature Film",
        actors: ["Bae Sung-woo", "Sung Dong-il", "Jang Young-nam", "Kim Hye-jun", "Jo Yi-hyun"],
        trailer: "https://www.youtube.com/watch?v=Jx11DtfiPwc",
        rating: 3.8,
        keywords: ["possession", "demon", "family", "exorcism", "shape-shifter"],
        kind: "R"
    },
    {
        title: "The Closet",
        pics: "The Closet.jpg",
        epilogue: "After his wife’s death, Sang-Won moves to a new home with his daughter Yi-Na, hoping to start fresh. However, mysterious events lead to his daughter's disappearance. A stranger tells him to search for her in the closet, uncovering a terrifying supernatural entity behind the tragedies.",
        date_released: "February 5, 2020",
        category: "Horror, Mystery",
        type: "Feature Film",
        actors: ["Ha Jung-woo", "Kim Nam-gil", "Heo Yool", "Shin Hyun-bin", "Kim Si-ah"],
        trailer: "https://www.youtube.com/watch?v=CrxVubVUwRk",
        rating: 3.7,
        keywords: ["supernatural", "missing child", "ghost", "closet", "horror"],
        kind: "R"
    },
    {
        title: "Alive",
        pics: "Alive.jpg",
        epilogue: "As a fast-spreading zombie outbreak ravages the city, a young man remains trapped in his apartment. With no communication, no food, and no hope, he must find a way to survive. The movie offers a modern take on the zombie genre, focusing on isolation and survival in the digital age.",
        date_released: "September 8, 2020",
        category: "Horror, Action, Thriller",
        type: "Feature Film",
        actors: ["Yoo Ah-in", "Park Shin-hye", "Lee Hyun-wook", "Jin So-yeon", "Oh Hye-won"],
        trailer: "https://www.youtube.com/watch?v=jQ8CCg1tOqc",
        rating: 3.9,
        keywords: ["zombies", "apocalypse", "isolation", "survival", "social media"],
        kind: "R"
    },
    {
        title: "Zombie for Sale",
        pics: "Zombie for Sale.jpg",
        epilogue: "A pharmaceutical company's illegal experiments create a zombie, and a quirky family in a rural town sees this as a business opportunity. The film blends horror and comedy, providing a unique and light-hearted take on the zombie genre, while still delivering suspense and scares.",
        date_released: "July 1, 2020",
        category: "Horror, Comedy, Drama",
        type: "Feature Film",
        actors: ["Jung Jae-young", "Kim Nam-gil", "Uhm Ji-won", "Lee Soo-kyung", "Jung Ga-ram"],
        trailer: "https://www.youtube.com/watch?v=FaESvu-aoA4",
        rating: 4.2,
        keywords: ["zombies", "comedy", "family", "pharmaceutical", "experiments"],
        kind: "PG-13"
    },
    {
        title: "Peninsula",
        pics: "Peninsula.jpg",
        epilogue: "Set four years after *Train to Busan*, *Peninsula* follows a group of survivors trying to escape a desolate Korean peninsula overrun by zombies. The movie amps up the action with high-octane car chases, survival battles, and a fight for freedom. It's an action-packed sequel with a dystopian twist.",
        date_released: "August 7, 2020",
        category: "Horror, Action, Thriller",
        type: "Feature Film",
        actors: ["Gang Dong-won", "Lee Jung-hyun", "Lee Re", "Kwon Hae-hyo", "Kim Min-jae"],
        trailer: "https://www.youtube.com/watch?v=yVucSRLLeIM",
        rating: 3.5,
        keywords: ["zombies", "dystopia", "survival", "sequel", "post-apocalypse"],
        kind: "R"
    },
    {
        title: "The Call",
        pics: "The Call.jpg",
        director: 'Double D',
        epilogue: "Two women living in different times, but in the same house, are connected by a phone call. As they manipulate each other's pasts, a dangerous game of cat and mouse ensues, leading to shocking consequences. This psychological horror blends time-travel elements with intense suspense and a twisted plot.",
        date_released: "November 27, 2020",
        category: "Horror, Thriller, Mystery",
        type: "Feature Film",
        actors: ["Park Shin-hye", "Jeon Jong-seo", "Kim Sung-ryung", "Lee El", "Oh Jung-se"],
        trailer: "https://www.youtube.com/watch?v=UOqSi-_cXeE",
        rating: 4.3,
        keywords: ["time-travel", "phone call", "serial killer", "psychological", "thriller"],
        kind: "R"
    },
    {
        title: "The 8th Night",
        pics: "The 8th Night.jpg",
        epilogue: "With prayer beads in one hand and an axe in the other, a monk hunts down an ancient spirit possessing humans and unleashing terror. *The 8th Night* offers a mix of religious horror and suspense, drawing from Buddhist mythology. The movie blends mystery and supernatural elements, making it a captivating watch.",
        date_released: "July 2, 2021",
        category: "Horror, Mystery, Thriller",
        type: "Feature Film",
        actors: ["Lee Sung-min", "Park Hae-joon", "Kim You-jung", "Nam Da-reum", "Choi Jin-ho"],
        trailer: "https://www.youtube.com/watch?v=fPr8jJxT7-A",
        rating: 3.6,
        keywords: ["monk", "ancient spirit", "exorcism", "Buddhist mythology", "supernatural"],
        kind: "R"
    },
    {
        title: "The Swordsman",
        pics: "The Swordsman.jpg",
        epilogue: "A retired swordsman embarks on a quest to rescue his kidnapped daughter from a powerful warlord. Set in the Joseon era, *The Swordsman* showcases traditional Korean swordsmanship, with beautifully choreographed fight scenes and a story centered around loyalty, honor, and family.",
        date_released: "September 23, 2020",
        category: "Action, Historical, Drama",
        type: "Feature Film",
        actors: ["Jang Hyuk", "Kim Hyun-soo", "Joe Taslim", "Jung Man-sik", "Choi Jin-ho"],
        trailer: "https://www.youtube.com/watch?v=f_E_LiqO2To",
        rating: 4.0,
        keywords: ["swordsmanship", "Joseon era", "kidnapping", "family", "honor"],
        kind: "PG-13"
    },
    {
        title: "The Roundup",
        pics: "The Roundup.jpg",
        epilogue: "Sequel to *The Outlaws*, *The Roundup* follows a relentless detective as he pursues a violent criminal who has fled to Vietnam. Packed with brutal action sequences and dark humor, the film delivers intense chase scenes and an unflinching portrayal of justice.",
        date_released: "May 18, 2022",
        category: "Action, Crime, Thriller",
        type: "Feature Film",
        actors: ["Ma Dong-seok", "Son Suk-ku", "Choi Gwi-hwa", "Park Ji-hwan", "Heo Dong-won"],
        trailer: "https://www.youtube.com/watch?v=H-T6jRxiv6I",
        rating: 4.3,
        keywords: ["detective", "Vietnam", "criminal", "justice", "chase scenes"],
        kind: "R"
    },
    {
        title: "The Witch 2",
        pics: "The Witch 2.jpg",
        epilogue: "This sequel to *The Witch: Part 1. The Subversion* introduces a new girl with deadly abilities, as she escapes from a secret laboratory and faces a world full of enemies. The film blends intense action sequences with a dark narrative about superhuman experiments.",
        date_released: "June 15, 2022",
        category: "Action, Sci-Fi, Mystery",
        type: "Feature Film",
        actors: ["Shin Si-ah", "Park Eun-bin", "Seo Eun-soo", "Jin Goo", "Sung Yoo-bin"],
        trailer: "https://www.youtube.com/watch?v=7fn-nre1GfU",
        rating: 4.1,
        keywords: ["superhuman", "experiments", "sequel", "escape", "mystery"],
        kind: "R"
    },
    {
        title: "Special Delivery",
        pics: "Special Delivery.jpg",
        epilogue: "A skilled driver with a knack for delivering anything to anyone becomes entangled in a dangerous situation involving a child and a criminal gang. *Special Delivery* features thrilling car chases and a fast-paced story that keeps the audience engaged.",
        date_released: "January 12, 2022",
        category: "Action, Crime, Thriller",
        type: "Feature Film",
        actors: ["Park So-dam", "Song Sae-byeok", "Kim Eui-sung", "Yeon Woo-jin", "Jung Hyun-jun"],
        trailer: "https://www.youtube.com/watch?v=HTUX83R4N9k",
        rating: 3.9,
        keywords: ["driver", "car chase", "criminal gang", "thriller", "child"],
        kind: "PG-13"
    },
    {
        title: "Yaksha Ruthless Operations",
        pics: "Yaksha Ruthless Operations.jpg",
        epilogue: "An elite black ops team leader, code-named Yaksha, embarks on a deadly mission in Shenyang, China, to take down an international crime syndicate. *Yaksha: Ruthless Operations* is an intense action-thriller full of espionage, betrayal, and fast-paced action sequences.",
        date_released: "April 8, 2022",
        category: "Action, Spy, Thriller",
        type: "Feature Film",
        actors: ["Sol Kyung-gu", "Park Hae-soo", "Yang Dong-geun", "Lee El", "Jinyoung"],
        trailer: "https://www.youtube.com/watch?v=bgFQv1nBh0A",
        rating: 4.0,
        keywords: ["black ops", "crime syndicate", "espionage", "betrayal", "spy thriller"],
        kind: "R"
    },
    {
        title: "Carter",
        pics: "Carter.jpg",
        epilogue: "A man wakes up with no memory, only to find himself in the middle of a deadly mission with a device implanted in his head. With non-stop action and intense fight scenes, *Carter* keeps the audience on edge as the protagonist races against time to complete his mission.",
        date_released: "August 5, 2022",
        category: "Action, Thriller",
        type: "Feature Film",
        actors: ["Joo Won", "Lee Sung-jae", "Jeong So-ri", "Kim Bo-min", "Jung Jae-young"],
        trailer: "https://www.youtube.com/watch?v=gk5IwfA8K7g",
        rating: 3.8,
        keywords: ["amnesia", "device", "mission", "action thriller", "fight scenes"],
        kind: "R"
    },

    {
        title: "Confidential Assignment 2",
        pics: "Confidential Assignment 2.jpg",
        epilogue: "In this action-packed sequel, a South Korean detective teams up with a North Korean officer and an FBI agent to catch an international criminal. *Confidential Assignment 2* offers a thrilling mix of action, comedy, and international intrigue.",
        date_released: "September 7, 2022",
        category: "Action, Comedy, Thriller",
        type: "Feature Film",
        actors: ["Hyun Bin", "Yoo Hae-jin", "Yoona", "Daniel Henney", "Jin Seon-kyu"],
        trailer: "https://www.youtube.com/watch?v=vTy6TM0tZKY",
        rating: 4.1,
        keywords: ["international", "criminal", "South Korea", "North Korea", "FBI"],
        kind: "PG-13"
    },
    {
        title: "Kill Boksoon",
        pics: "Kill Boksoon.jpg",
        epilogue: "A legendary contract killer juggles her dangerous job with raising a teenage daughter. *Kill Boksoon* features intense action scenes, a strong female lead, and a storyline that balances action with emotional depth.",
        date_released: "2023",
        category: "Action, Drama, Crime",
        type: "Feature Film",
        actors: ["Jeon Do-yeon", "Sol Kyung-gu", "Kim Si-a", "Esom", "Koo Kyo-hwan"],
        trailer: "https://www.youtube.com/watch?v=SXRP_a2aZtM",
        rating: 4.2,
        keywords: ["contract killer", "motherhood", "female lead", "crime", "action drama"],
        kind: "R"
    },
    {
        title: "Ashfall",
        pics: "Ashfall.jpg",
        epilogue: "As a volcano on the China-North Korea border erupts, triggering massive earthquakes, a South Korean demolition expert teams up with a North Korean agent to prevent further disasters. The film blends high-octane action sequences with disaster movie tropes, offering an adrenaline-pumping ride.",
        date_released: "December 19, 2019",
        category: "Action, Disaster",
        type: "Feature Film",
        actors: ["Lee Byung-hun", "Ha Jung-woo", "Ma Dong-seok", "Jeon Hye-jin", "Bae Suzy"],
        trailer: "https://www.youtube.com/watch?v=5pHVF2hoZSM",
        rating: 4.1,
        keywords: ["volcano", "disaster", "earthquake", "South Korea", "North Korea"],
        kind: "PG-13"
    },

    {
        title: "Exit",
        pics: "Exit.jpg",
        epilogue: "A failed rock climber must use his skills to save his family and others trapped in a building as a deadly gas spreads through the city. With its blend of humor and suspense, *Exit* delivers heart-pounding action and a story of personal redemption.",
        date_released: "July 31, 2019",
        category: "Action, Comedy, Disaster",
        type: "Feature Film",
        actors: ["Jo Jung-suk", "Im Yoon-ah", "Ko Doo-shim", "Park In-hwan", "Kim Ji-young"],
        trailer: "https://www.youtube.com/watch?v=XyXzv2X9XnY",
        rating: 4.2,
        keywords: ["rock climbing", "disaster", "gas", "survival", "comedy"],
        kind: "PG-13"
    },
    {
        title: "The Man Standing Next",
        pics: "The Man Standing Next.jpg",
        epilogue: "Based on real events, this political thriller follows the power struggles within South Korea's government during the 1970s. It centers around the director of the Korean Central Intelligence Agency, who plots to overthrow the president. The film combines political intrigue with action-packed sequences.",
        date_released: "January 22, 2020",
        category: "Action, Drama, Thriller",
        type: "Feature Film",
        actors: ["Lee Byung-hun", "Lee Sung-min", "Kwak Do-won", "Lee Hee-joon", "Kim So-jin"],
        trailer: "https://www.youtube.com/watch?v=IsjJUEgH0Jw",
        rating: 4.0,
        keywords: ["political thriller", "government", "South Korea", "power struggle", "1970s"],
        kind: "R"
    },
    {
        title: "Time to Hunt",
        pics: "Time to Hunt.jpg",
        epilogue: "Set in a dystopian future, a group of young men plan a heist in hopes of escaping their grim reality. However, they find themselves hunted by a relentless assassin. *Time to Hunt* delivers intense action sequences and explores themes of survival and betrayal.",
        date_released: "April 23, 2020",
        category: "Action, Crime, Thriller",
        type: "Feature Film",
        actors: ["Lee Je-hoon", "Ahn Jae-hong", "Choi Woo-shik", "Park Jung-min", "Park Hae-soo"],
        trailer: "https://www.youtube.com/watch?v=uwq9L9aoftU",
        rating: 3.9,
        keywords: ["heist", "assassin", "dystopia", "survival", "betrayal"],
        kind: "R"
    },

    {
        title: "Seobok",
        pics: "Seobok.jpg",
        epilogue: "The story follows a former intelligence agent tasked with protecting Seobok, the first human clone, who possesses the secret to eternal life. As they are hunted by various forces, the film combines elements of sci-fi and action with a deep exploration of morality and humanity.",
        date_released: "April 15, 2021",
        category: "Action, Sci-Fi, Thriller",
        type: "Feature Film",
        actors: ["Gong Yoo", "Park Bo-gum", "Jo Woo-jin", "Jang Young-nam", "Park Byung-eun"],
        trailer: "https://www.youtube.com/watch?v=r1IU0CzAnKw",
        rating: 3.9,
        keywords: ["human clone", "eternal life", "sci-fi", "intelligence agent", "morality"],
        kind: "PG-13"
    },
    {
        title: "Kingdom Ashin of the North",
        pics: "Kingdom_Ashin_of_the_North.jpg",
        epilogue: "This special episode of *Kingdom* explores the origins of the zombie outbreak and follows Ashin, a woman seeking revenge after her tribe and family are destroyed. Blending historical drama with horror, the film delves into the darker side of human nature and the devastating consequences of unchecked ambition.",
        date_released: "July 23, 2021",
        category: "Horror, Action, Drama",
        type: "Feature Film",
        actors: ["Jun Ji-hyun", "Park Byung-eun", "Kim Shi-a", "Koo Kyo-hwan", "Kim Roe-ha"],
        trailer: "https://www.youtube.com/watch?v=26J1F8Kngkc",
        rating: 4.5,
        keywords: ["zombies", "revenge", "historical", "epidemic", "survival"],
        kind: "R"
    },

    {
        title: "Midnight",
        pics: "Midnight.jpg",
        epilogue: "A tense and terrifying thriller following a deaf woman who becomes the target of a relentless serial killer. As she tries to escape, her lack of hearing makes her vulnerable, but she uses her wit and courage to fight back. The film delivers suspenseful chase sequences and a gripping cat-and-mouse dynamic.",
        date_released: "June 30, 2021",
        category: "Thriller, Horror",
        type: "Feature Film",
        actors: ["Jin Ki-joo", "Wi Ha-joon", "Park Hoon", "Kil Hae-yeon", "Kim Hye-yoon"],
        trailer: "https://www.youtube.com/watch?v=78pgf-IrLoM",
        rating: 4.0,
        keywords: ["serial killer", "deaf woman", "suspense", "thriller", "chase"],
        kind: "R"
    },
    {
        title: "Unlocked",
        pics: "Unlocked.jpg",
        epilogue: "When a woman's lost smartphone falls into the hands of a sociopathic hacker, her life spirals out of control as he begins to invade her privacy and manipulate her every move. This tech-focused thriller sheds light on the dangers of a hyperconnected world, blending suspense with themes of control, privacy invasion, and paranoia.",
        date_released: "February 17, 2023",
        category: "Thriller, Mystery",
        type: "Feature Film",
        actors: ["Im Si-wan", "Chun Woo-hee", "Kim Ye-won", "Park Ho-san", "Jeon Jin-oh"],
        trailer: "https://www.youtube.com/watch?v=ZXtdzNKpNzg",
        rating: 4.2,
        keywords: ["smartphone", "privacy", "hacker", "stalking", "manipulation"],
        kind: "PG-13"
    },
    {
        title: "Spiritwalker",
        pics: "Spiritwalker.jpg",
        epilogue: "A man wakes up every 12 hours in a different body, with no memory of who he is or how he got there. As he tries to piece together his fragmented identity, he finds himself hunted by mysterious forces. *Spiritwalker* combines supernatural elements with action-packed sequences, creating a unique blend of mystery and suspense.",
        date_released: "November 24, 2021",
        category: "Thriller, Mystery, Fantasy",
        type: "Feature Film",
        actors: ["Yoon Kye-sang", "Park Yong-woo", "Lim Ji-yeon", "Yoo Seung-mok", "Lee Sung-wook"],
        trailer: "https://www.youtube.com/watch?v=syFZfO_wfMQ",
        rating: 3.9,
        keywords: ["body-swapping", "identity", "action", "supernatural", "memory loss"],
        kind: "PG-13"
    },

    {
        title: "The Cursed Dead Man’s Prey",
        pics: "The Cursed Dead.jpg",
        epilogue: "A journalist becomes embroiled in a series of bizarre murders linked to resurrected corpses, each controlled by a mysterious force. As she investigates, she uncovers an ancient curse tied to the victims. The film blends crime, horror, and the supernatural, delivering a suspenseful and eerie experience.",
        date_released: "July 28, 2022",
        category: "Horror, Mystery, Thriller",
        type: "Feature Film",
        actors: ["Uhm Ji-won", "Jung Ji-so", "Oh Yoon-ah", "Jung Moon-sung", "Ko Kyu-pil"],
        trailer: "https://www.youtube.com/watch?v=FHT1_Li0TyM",
        rating: 3.8,
        keywords: ["curse", "resurrected corpses", "supernatural", "investigation", "murder"],
        kind: "R"
    },
    {
        title: "The Ghost Station",
        pics: "The Ghost Station.jpg",
        epilogue: "A paranormal event at a subway station starts a series of terrifying encounters. As people begin to disappear, a group of investigators uncovers a dark history linked to the station. The film mixes supernatural elements with urban horror, creating a suspenseful atmosphere of dread and fear.",
        date_released: "March 2023",
        category: "Horror, Mystery",
        type: "Feature Film",
        actors: ["Kim Bo-ra", "Kim Jae-hyun", "Shin So-yul", "Jung Yi-seo", "Kim Mi-kyung"],
        trailer: "https://www.youtube.com/watch?v=9N35rNYL5eg",
        rating: 3.4,
        keywords: ["subway station", "disappearance", "paranormal", "urban horror", "investigation"],
        kind: "PG-13"
    },
    {
        title: "Cobweb",
        pics: "Cobweb.jpg",
        epilogue: "A horror-comedy following a director obsessed with completing his movie during a stormy night. As production continues, strange occurrences and eerie events begin to unfold, blurring the line between fiction and reality. The film offers a meta take on the horror genre, blending comedy with chilling moments.",
        date_released: "May 2023",
        category: "Horror, Comedy",
        type: "Feature Film",
        actors: ["Song Kang-ho", "Jeon Yeo-been", "Im Soo-jung", "Oh Jung-se", "Jung Yoon-chae"],
        trailer: "https://www.youtube.com/watch?v=G_uL-yV-VS8",
        rating: 4.0,
        keywords: ["horror-comedy", "director", "movie production", "fiction vs reality", "storm"],
        kind: "PG-13"
    },
    {
        title: "Sleep",
        pics: "Sleep.jpg",
        epilogue: "A couple's peaceful life takes a disturbing turn when one of them begins experiencing terrifying sleep-related events. As the boundary between dreams and reality blurs, they must confront the deep-seated fears and traumas that surface. *Sleep* is a psychological horror-drama that explores the fragility of the mind and the terrifying power of the subconscious.",
        date_released: "2023",
        category: "Horror, Drama, Psychological",
        type: "Feature Film",
        actors: ["Jung Yu-mi", "Lee Sun-kyun", "Kim Soo-jin", "Kim Kyung-ik", "Jung Ga-ram"],
        trailer: "https://www.youtube.com/watch?v=VJSHgG7A45k",
        rating: 4.0,
        keywords: ["sleep disorder", "psychological horror", "nightmares", "subconscious", "couple"],
        kind: "R"
    },
];
